### ISSUE TITLE
Loconet interface (Build your own)

### ISSUE THREAD

**Issue by ATrain80** [tanner87661/IoTTStick#19]
According to your schematics for the Loconet communication board, I have created an adjusted one. Since I do need only the Loconet communication and no separate loconet.
However I have forgotten to connect pins 2 and 5 of the loconet RJ45 connector.
For that I have created a wire bridge between the pin 5 and RXD. 
But at my DCC command station Digikeijs DR5000 the Loconet led TX keeps active. And I don't seem to have any proper loconet communication between the command station and my breakout board. I do not receive any commands on ESP32, and commands from ESP32 don't end up at the command station.

Can you please help me out? Thanks.

This is my schematic:
[ESP32 loconet breakout board.pdf](https://github.com/tanner87661/IoTTStick/files/8257648/ESP32.loconet.breakout.board.pdf)

**Comment by tanner87661** [comment]
You pretty much rotated the connection lines. Please verify with the original schematics.

*	TXD should be 3.3V
*	RXD is GND
*	GND is RXD
*	3.3V is TXD
*	And you also need to connect from LocoNet GND (pins 2,5) to board GND so that the comparator has a reference voltage.

Hans

 

 

From: ATrain80 ***@***.***> 
Sent: Tuesday, March 15, 2022 6:42 PM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Loconet interface (Build your own) (Issue #19)

 

According to your schematics for the Loconet communication board, I have created an adjusted one. Since I do need only the Loconet communication and no separate loconet.
However I have forgotten to connect pins 2 and 5 of the loconet RJ45 connector.
For that I have created a wire bridge between the pin 5 and RXD.
But at my DCC command station Digikeijs DR5000 the Loconet led TX keeps active. And I don't seem to have any proper loconet communication between the command station and my breakout board. I do not receive any commands on ESP32, and commands from ESP32 don't end up at the command station.

Can you please help me out? Thanks.

This is my schematic:
ESP32 loconet breakout board.pdf <https://github.com/tanner87661/IoTTStick/files/8257648/ESP32.loconet.breakout.board.pdf>

**Comment by ATrain80** [comment]
Thanks alot, I see what went wrong.
The grove connector pin numbers are not the same as on your schematics. Pin 1 is pin 4, Pin 2 is pin 3 and vice versa.
That explains the rotation of connection lines.

I will create a GND connection for pin 2 and 5, and connect my module correctly to the ESP32.
Will give an update if it solves the issues.

**Comment by ATrain80** [comment]
Rewired the ESP32 to the Loconet PCB and connected the ground to pins 2 and 5 of the RJ45.
Tried again Today, first data was not received correctly. 
But I have changed the UART speed in the library from 9600 to 16667. 
And it is working fine now. Thanks alot.
