### ISSUE TITLE
Placement of components at jlcpcb

### ISSUE THREAD

**Issue by meinarsson** [tanner87661/IoTTStick#25]
I am trying to order a few loconet boards from jlcpcb. The components are placed at an offset in the preview.  It says that jlcpcb will adjust the placement, but since this is my first time trying to use jlcpcb i am unsure if this is a normal offset or if I did something wrong.
Does the attached picture look like it does when you order pcbs?
![image](https://user-images.githubusercontent.com/27996200/168148230-9421074c-e26d-40e8-9989-f465aba1bccd.png)

/Magnus

**Comment by tanner87661** [comment]
No, that does not look normal.

Anyway, I just uploaded the design files from my latest order to https://github.com/tanner87661/IoTTStick/tree/master/Communication%20Modules/LocoNet%20Interface/Rev3

You may want to use those, they worked without problem. Also, I changed a few part numbers to stay as much as possible with standard parts to avoid setup fees. No changes to the schematics or layout, though.

I just tested with the new files and I am also getting this offset now. Seems like a problem in their web page. It looks systematic and they will fix the placement.

**Comment by tanner87661** [comment]
I just tested with the new files and I am also getting this offset now. Seems like a problem in their web page. It looks systematic and they will fix the placement.

 

From: meinarsson ***@***.***> 
Sent: Thursday, May 12, 2022 2:58 PM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Placement of components at jlcpcb (Issue #25)

 

I am trying to order a few loconet boards from jlcpcb. The components are placed at an offset in the preview. It says that jlcpcb will adjust the placement, but since this is my first time trying to use jlcpcb i am unsure if this is a normal offset or if I did something wrong.
Does the attached picture look like it does when you order pcbs?
 <https://user-images.githubusercontent.com/27996200/168148230-9421074c-e26d-40e8-9989-f465aba1bccd.png> 

/Magnus
